### ISSUE TITLE
"browser.setMaxListeners is not a function" error while using stealth plugin

### ISSUE THREAD

**Issue by Beenyaa** [berstend/puppeteer-extra#270]
I made a scraper using the stealth plugin to help avoid detection and all of the sudden the whole scraper broke out of the blue. 

Not sure what is causing the error as it was working just fine a few days ago, I haven't updated any of the packages either recently (until today which still hasn't solved my problem).

If I comment out the line `puppeteer.use(StealthPlugin())` the scraper works fine, but obviously it won't be as stealthy as I'd want it to be. If I don't comment out the line I get presented with this error: `browser.setMaxListeners is not a function` and the whole script stops at opening the browser.

Tried looking this issue up, but couldn't find anything helpful. I am a rookie, this probably won't be enough info for you to go off of.

**Comment by brunogaspar** [comment]
You should use the latest versions of puppeteer-extra and it's plugins since this issue is already fixed on them.

If it's not working, let us know what exact versions you're using.

**Comment by Beenyaa** [comment]
So I updated the packages but the issue still persists, here are the versions I am using currently:
puppeteer-extra-plugin-stealth@2.4.14
puppeteer-extra-plugin@3.1.7
puppeteer@5.2.1

**Comment by brunogaspar** [comment]
I can't reproduce, you must have something that's not properly up to date, try to remove both the `node_modules/` directory and the `package-lock.json` file or `yarn.lock` file and try to install it again.

Dependencies:

```
"dependencies": {
    "puppeteer": "^5.2.1",
    "puppeteer-extra": "^3.1.13",
    "puppeteer-extra-plugin-stealth": "^2.4.14"
}
```

Test code copied directly from the readme:

```js
// puppeteer-extra is a drop-in replacement for puppeteer,
// it augments the installed puppeteer with plugin functionality
const puppeteer = require('puppeteer-extra')

// add stealth plugin and use defaults (all evasion techniques)
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

// puppeteer usage as normal
puppeteer.launch({ headless: true }).then(async browser => {
  console.log('Running tests..')
  const page = await browser.newPage()
  await page.goto('https://bot.sannysoft.com')
  await page.waitFor(5000)
  await page.screenshot({ path: 'testresult.png', fullPage: true })
  await browser.close()
  console.log(`All done, check the screenshot. ✨`)
})
```

**Comment by Beenyaa** [comment]
Thank you, this has done it!

**Comment by brunogaspar** [comment]
Awesome, glad it helped!
