### ISSUE TITLE
[Bug] captcha error: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by alamothe** [berstend/puppeteer-extra#452]
Hello, 
We are getting this strange error when using your plugin + 2captcha on https://www.txtag.org/txtagstorefront/en/login. Is this related to a recent update? It used to work very recently. Thanks!

```
PuppeteerExtraPluginRecaptcha: An error occured during "getRecaptchaSolutions": { _vendor: 'recaptcha',
  provider: '2captcha',
  id: 'r47e8g9qcfup',
  requestAt: 2021-03-15T21:28:43.036Z,
  error:
   'Error: 2captcha error: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"' }
SNAPSHOT: Error
  step 1
  url: https://www.txtag.org/txtagstorefront/en/login
```

**Comment by alamothe** [comment]
Downgrading to `3.3.3` fixes the issue.

**Comment by Inamacio** [comment]
Downgrading didn't work
`PuppeteerExtraPluginRecaptcha: An error occured during "getRecaptchaSolutions": {
  _vendor: 'recaptcha',
  provider: '2captcha',
  id: 'svirlav6ct4h',
  requestAt: 2021-03-15T21:55:21.362Z,
  error: 'Error: 2captcha error: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"'
}`

**Comment by Porkts** [comment]
Same with me

**Comment by alamothe** [comment]
@Inamacio Make sure you pin the version to `3.3.3` (do not use ~ or ^ since it will go to 3.3.5)

**Comment by brunogaspar** [comment]
Are you sure 3.3.4 does not work? The change done [here](https://github.com/berstend/puppeteer-extra/commit/c9680da37ad88c04c83a767e14cbeedead30f6f8) only affects the new 3.3.5 version.

**Comment by brunogaspar** [comment]
v3.3.6 which was just released should fix this.

**Comment by dunstorm** [comment]
> v3.3.6 which was just released should fix this.

@brunogaspar Still having this issue after updating to v3.3.6

```
PuppeteerExtraPluginRecaptcha: An error occured during "getRecaptchaSolutions": {
  _vendor: 'recaptcha',
  provider: '2captcha',
  id: 'n6ydheuqjap5',
  requestAt: 2021-03-16T11:30:21.778Z,
  error: 'Error: 2captcha error: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"'
}
```

**Comment by berstend** [comment]
@dunstorm this should/cannot happen with 3.3.6 as I reverted the code to use http 🤔 

Can you double check your recaptcha plugin version by running the following command in your project directory?
```
npx envinfo@latest --system --binaries --npmPackages '*(puppeteer*|playwright*|automation-extra*|@extra*)'
```

**Comment by berstend** [comment]
Those would be the ways to install the new version specifically:
```
yarn add puppeteer-extra-plugin-recaptcha@3.3.6
// or
npm install puppeteer-extra-plugin-recaptcha@3.3.6
```

**Comment by berstend** [comment]
Oh damn, I forgot to re-build the files - hotfix is underway

**Comment by berstend** [comment]
@alamothe @Inamacio @Porkts please upgrade to `puppeteer-extra-plugin-recaptcha@3.3.7` which (properly) reverts back to use the http API - apologies for the inconvenience. 😓

**Comment by berstend** [comment]
Confirmed the fix is live:
```bash
yarn init -y
yarn add puppeteer-extra-plugin-recaptcha@3.3.7
cat node_modules/puppeteer-extra-plugin-recaptcha/package.json| grep version
  "version": "3.3.7",
cat node_modules/puppeteer-extra-plugin-recaptcha/dist/provider/2captcha-api.js | grep apiInUrl
var apiInUrl = 'http://2captcha.com/in.php';
```

**Comment by alamothe** [comment]
@berstend Thanks for the quick fix! 

To answer your question, I haven't checked `3.3.4` — I reverted to `3.3.3` based on the release date as I knew it used to work around that time.

**Comment by alamothe** [comment]
@berstend So should we talk to 2captcha about them supporting https? Their customer service is pretty good in my experience

**Comment by Tyler-Murphy** [comment]
I just noticed this issue when I was looking at the latest PR to switch to HTTPS: https://github.com/berstend/puppeteer-extra/pull/457

I think that error message means that the `http` module was used to try to make an HTTPS request, not that 2captcha doesn't support HTTPS. See https://stackoverflow.com/questions/34147372/node-js-error-protocol-https-not-supported-expected-http. From what I've seen, 2captcha supports https and I've never had a problem using it.

That new PR removes the `http` module entirely, so if there was a bug in the logic about when to use the `http` module and when to use the `https`, it might be fixed.

**Comment by berstend** [comment]
@Tyler-Murphy yeah, that was the issue :-) #457 seems to address that.
