### ISSUE TITLE
Latest stealth plugin detected by Google

### ISSUE THREAD

**Issue by teewoeijer** [berstend/puppeteer-extra#578]
The stealth plugin had been working fine on Google's website, however it stopped working recently. The website shows "This browser or app may not be secure" error after submitting the username.

my package version:
puppeteer-extra-plugin-stealth@2.8.2
puppeteer-extra@3.2.3

Below is my code:
```
(async () => {
  const puppeteer = require('puppeteer-extra')
  const StealthPlugin = require('puppeteer-extra-plugin-stealth')
  puppeteer.use(StealthPlugin())  
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://accounts.google.com/signin/v2/identifier?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin');
  await page.type('input', 'demo123', {delay: 20})
  const elements = await page.$x('//span[text()="Next"]')
  await elements[0].click() 
  await page.waitForTimeout(3000);
  await browser.close();
})();
```

**Comment by pierreminiggio** [comment]
I use a youtube uploader package that relies on the stealth plugin, we've got issues logging in to Google as well :
https://github.com/fawazahmed0/youtube-uploader/issues/48

**Comment by UGLHong** [comment]
same issue here =(

**Comment by Bramzor** [comment]
Same issue here.  Seems that Google can detect it. Even when using:

            executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
            userDataDir: userDataDir,
            headless: false,

**Comment by teewoeijer** [comment]
Okay I found something that might be useful. If using invalid user agent with stealth plugin can actually bypass the detection. However, you will probably get recaptcha since its invalid user agent, but if you can solve the recaptcha you can actually login.

So I think maybe the stealth plugin's user-agent-override package may be the answer for this fix.

My code:
```
(async () => {
  const puppeteer = require('puppeteer-extra')
  const StealthPlugin = require('puppeteer-extra-plugin-stealth')
  puppeteer.use(StealthPlugin())  
  const browser = await puppeteer.launch({ headless: false});
  const page = await browser.newPage();
  await page.setUserAgent("'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'");
  await page.goto('https://accounts.google.com/signin/v2/identifier?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin');
  await page.type('input', 'demo123', {delay: 20})
  const elements = await page.$x('//span[text()="Next"]')
  await elements[0].click() 
  await page.waitForTimeout(30000);
  await browser.close();
})();

```

**Comment by berstend** [comment]
Fixed in #579:
```
Successfully published:
 - puppeteer-extra-plugin-stealth@2.9.0
```
[Coffee](https://www.buymeacoffee.com/brstnd) donations accepted 😄

**Comment by teewoeijer** [comment]
@berstend Thanks its working again with version 2.9.0. However, the problem persists while running in headless mode.

**Comment by 456478** [comment]
It is working in headless mode. Bypass CSP geniuses

**Comment by teewoeijer** [comment]
> It is working in headless mode. Bypass CSP geniuses

Yes added await page.setBypassCSP(true) and its working. thanks.

**Comment by pierreminiggio** [comment]
I just wanna say thanks for the quick response on this issue ! ♥
I'll get you a coffee later.

**Comment by signaldev1** [comment]
hello @berstend  this error is showing again do you have any idea ??

**Comment by LinkTree3** [comment]
Google started to detect puppeteer extra stealth for me as well. :(
It won't let login to some of  the few accounts I'm managing.

**Comment by berstend** [comment]
This issue has been closed in favor of #588

A possible workaround has been mentioned here: https://github.com/berstend/puppeteer-extra/issues/668#issuecomment-1175380080

**Comment by signaldev1** [comment]
Hey @berstend , Once again, the issue has emerged today

**Comment by bashar-odeh** [comment]
Any solution to this issue?

**Comment by Astralights366** [comment]
If you have these arguments in your browser startup:
``args: [ 
`--disable-web-security`,
`--allow-running-insecure-content`,
]``

removing them (or one of them) solved the issue for me

**Comment by vladtreny** [comment]
^ this is probably because they detect via iframe
